export type Product = {
  id: string
  name: string
  brand: string
  category: string
  price: string
  image: string
  tag?: string
  description: string
  link: string
}

export const products: Product[] = [
  {
    id: "cargador-100w",
    name: "UGREEN 130W Cargador Coche USB-C",
    brand: "Ugreen",
    category: "Cargadores de Carro",
    price: "Q300.00",
    image: "/products/car-100w-usb-c.png",
    tag: "Oferta",
    description: "Carga hasta 3 dispositivos a la vez con salida combinada de 130W, ideal para laptop y celular en el auto.",
    link: "https://shop.unyxgt.com/products/ugreen-cargador-100w",
  },
  {
    id: "bateria-portatil-130w",
    name: "UGREEN Batería Portátil 130W con Cable Incorporado — 20,000 mAh",
    brand: "Ugreen",
    category: "Baterías Portátiles",
    price: "Q550.00",
    image: "/products/powerbank-130w-20000mah.jpg",
    tag: "Oferta",
    description: "Power bank de 20,000 mAh con cable USB-C integrado y hasta 130W de salida para laptops y celulares.",
    link: "https://shop.unyxgt.com/products/ugreen-bateria-portatil-con-cable-incorporado-de-130w-20-000mah",
  },
  {
    id: "cable-usbc-100w-pd",
    name: "UGREEN Cable USB-C 100W PD — Carga Rápida 5A",
    brand: "Ugreen",
    category: "Cables",
    price: "A partir de Q190.00",
    image: "/products/cable-usbc-100w-pd-2m.jpg",
    tag: "Oferta",
    description: "Cable trenzado de nylon con carga rápida PD de 100W y transferencia de datos USB 2.0.",
    link: "https://shop.unyxgt.com/products/ugreen-cable-usb-c-100w-pd-carga-rapida-5a-2m",
  },
  {
    id: "cable-usbc-90-angulo",
    name: "UGREEN Cable USB-C 90° 100W — Ángulo Doble",
    brand: "Ugreen",
    category: "Cables",
    price: "A partir de Q180.00",
    image: "/products/cable-usbc-90-angulo.jpg",
    tag: "Oferta",
    description: "Conectores en ángulo de 90° con carga PD de 100W y construcción trenzada resistente a tirones.",
    link: "https://shop.unyxgt.com/products/ugreen-cable-usb-c-90-100w-angulo-90-doble-2m",
  },
  {
    id: "cable-usbc-retractil",
    name: "UGREEN Cable USB-C Retráctil 100W",
    brand: "Ugreen",
    category: "Cables",
    price: "Q195.00",
    image: "/products/cable-usbc-retractil.jpg",
    tag: "Oferta",
    description: "Cable retráctil con 4 niveles de longitud y carga rápida de 100W para iPhone, MacBook y Samsung.",
    link: "https://shop.unyxgt.com/products/ugreen-cable-usb-c-retractil-100w-iphone-macbook-samsung",
  },
  {
    id: "auto-145w-3en1",
    name: "UGREEN Cargador Auto 145W 3-en-1 — Retráctil QC",
    brand: "Ugreen",
    category: "Cargadores de Carro",
    price: "Q440.00",
    image: "/products/auto-145w-3en1.jpg",
    tag: "Oferta",
    description: "Cable USB-C retráctil integrado y hasta 145W combinados para cargar 4 dispositivos en el auto.",
    link: "https://shop.unyxgt.com/products/ugreen-cargador-auto-145w-3-en-1-3c1a-retractil-qc",
  },
  {
    id: "auto-90w-3en1",
    name: "UGREEN Cargador Auto 90W 3-en-1 — USB-C Retráctil",
    brand: "Ugreen",
    category: "Cargadores de Carro",
    price: "Q350.00",
    image: "/products/auto-90w-3en1.jpg",
    tag: "Oferta",
    description: "Cable retráctil integrado más puertos USB-C y USB-A para cargar 3 dispositivos a la vez en tu vehículo.",
    link: "https://shop.unyxgt.com/products/ugreen-cargador-auto-90w-3-en-1-usb-c-retractil",
  },
  {
    id: "smart-tag-cm816",
    name: "UGREEN CM816 Smart Tag — Localizador",
    brand: "Ugreen",
    category: "Accesorios",
    price: "Q150.00",
    image: "/products/smart-tag-cm816.jpg",
    tag: "Oferta",
    description: "Localizador compatible con Apple Find My, con batería reemplazable de hasta 2 años de duración.",
    link: "https://shop.unyxgt.com/products/ugreen-cm816-smart-tag-localizador-2-anos-bateria",
  },
  {
    id: "bolsa-organizador-lp285",
    name: "UGREEN LP285 Bolsa Organizador Digital",
    brand: "Ugreen",
    category: "Accesorios",
    price: "Q150.00",
    image: "/products/bolsa-organizador-lp285.jpg",
    tag: "Oferta",
    description: "Estuche compacto con correa para transportar y organizar cables, cargadores y otros accesorios.",
    link: "https://shop.unyxgt.com/products/ugreen-lp285-bolsa-organizador-digital-cables-y-accesorios",
  },
  {
    id: "mouse-vertical-m571p",
    name: "UGREEN M571P Mouse Vertical Ergonómico",
    brand: "Ugreen",
    category: "Accesorios",
    price: "Q290.00",
    image: "/products/mouse-vertical-m571p.jpg",
    tag: "Oferta",
    description: "Diseño vertical de 4000 DPI que reduce la tensión de muñeca, con conexión inalámbrica 2.4G.",
    link: "https://shop.unyxgt.com/products/ugreen-m571p-mouse-vertical-ergonomico-2-4g-4000-dpi",
  },
  {
    id: "nexode-100w-retractil",
    name: "UGREEN Nexode 100W GaN — Cable Retráctil Integrado",
    brand: "Ugreen",
    category: "Cargadores",
    price: "Q450.00",
    image: "/products/nexode-100w-retractil.jpg",
    tag: "Oferta",
    description: "Cargador GaN de 100W con cable en espiral retráctil integrado, carga hasta 4 dispositivos a la vez.",
    link: "https://shop.unyxgt.com/products/ugreen-nexode-100w-gan-cable-retractil-integrado-3-puertos",
  },
  {
    id: "nexode-65w-robot",
    name: "UGREEN Nexode 2ª Gen 65W GaN Robot",
    brand: "Ugreen",
    category: "Cargadores",
    price: "Q450.00",
    image: "/products/nexode-65w-robot.jpg",
    tag: "Oferta",
    description: "Cargador GaN de 65W con pantalla LED de expresiones y diseño magnético compacto tipo robot.",
    link: "https://shop.unyxgt.com/products/ugreen-nexode-2da-generacion-65w-gan-robot-qc4-0-pd3-0",
  },
  {
    id: "nexode-65w-4puertos",
    name: "UGREEN Nexode 65W GaN 4 Puertos Plegable",
    brand: "Ugreen",
    category: "Cargadores",
    price: "Q330.00",
    image: "/products/nexode-65w-4puertos.jpg",
    tag: "Oferta",
    description: "4 puertos de carga con enchufe plegable, ideal para viaje, con hasta 65W combinados.",
    link: "https://shop.unyxgt.com/products/ugreen-nexode-65w-gan-4-puertos-plegable-viaje",
  },
  {
    id: "nexode-pro-100w",
    name: "UGREEN Nexode Pro 100W GaN 3 Puertos + Cable",
    brand: "Ugreen",
    category: "Cargadores",
    price: "Q480.00",
    image: "/products/nexode-pro-100w.jpg",
    tag: "Oferta",
    description: "Carga inteligente de 3 dispositivos a la vez con tecnología GaNInfinity y hasta 100W en un solo puerto.",
    link: "https://shop.unyxgt.com/products/ugreen-nexode-pro-100w-gan-3-puertos-qc4-0-cable",
  },
  {
    id: "nexode-pro-65w-plano",
    name: "UGREEN Nexode Pro 65W GaN Plano Ultrafino",
    brand: "Ugreen",
    category: "Cargadores",
    price: "Q450.00",
    image: "/products/nexode-pro-65w-plano.jpg",
    tag: "Oferta",
    description: "Diseño plano y ultradelgado con 3 puertos y hasta 65W, perfecto para viajar sin bultos.",
    link: "https://shop.unyxgt.com/products/ugreen-nexode-pro-65w-gan-plano-3-puertos-ultrafino",
  },
  {
    id: "audifonos-s3-clip",
    name: "UGREEN S3 Clip Oreja BT 5.4 ENC HiFi",
    brand: "Ugreen",
    category: "Audífonos",
    price: "Q310.00",
    image: "/products/audifonos-s3-clip.jpg",
    tag: "Oferta",
    description: "Audífonos de oído abierto con Bluetooth 5.4, cancelación de ruido ENC y hasta 30 horas de batería.",
    link: "https://shop.unyxgt.com/products/ugreen-s3-clip-oreja-bt-5-4-enc-hifi",
  },
  {
    id: "audifonos-s6-magic",
    name: "UGREEN S6 Magic Audífonos Clip Oreja BT 5.4",
    brand: "Ugreen",
    category: "Audífonos",
    price: "Q490.00",
    image: "/products/audifonos-s6-magic.jpg",
    tag: "Oferta",
    description: "Diseño open-ear con drivers de 12 mm, resistencia IPX5 y hasta 30 horas de autonomía total.",
    link: "https://shop.unyxgt.com/products/ugreen-s6-magic-audifonos-clip-oreja-bt-5-4-lcd",
  },
  {
    id: "uno-100w-robot",
    name: "UGREEN Uno 100W GaN 4 Puertos Robot Nexode",
    brand: "Ugreen",
    category: "Cargadores",
    price: "Q590.00",
    image: "/products/uno-100w-robot.jpg",
    tag: "Oferta",
    description: "Cargador robot con pantalla TFT de expresiones, 4 puertos y hasta 100W para varios dispositivos.",
    link: "https://shop.unyxgt.com/products/ugreen-uno-100w-gan-4-puertos-robot-nexode",
  },
  {
    id: "cable-us334-90",
    name: "UGREEN US334 Cable USB-C 90° 100W",
    brand: "Ugreen",
    category: "Cables",
    price: "A partir de Q180.00",
    image: "/products/cable-us334-90.jpg",
    tag: "Oferta",
    description: "Cable en ángulo de 90° con chip E-Marker, carga PD de 100W y conectores chapados en oro.",
    link: "https://shop.unyxgt.com/products/ugreen-us334-cable-usb-c-90-100w-5a-pd-1m",
  },
]

export const categories = [
  {
    name: "Cargadores",
    count: 6,
    image: "/products/nexode-100w-retractil.jpg",
    link: "https://shop.unyxgt.com/collections/cargadores",
  },
  {
    name: "Cargadores de Carro",
    count: 3,
    image: "/products/car-100w-usb-c.png",
    link: "https://shop.unyxgt.com/collections/cargadores-de-carros",
  },
  {
    name: "Cables",
    count: 4,
    image: "/products/cable-usbc-100w-pd-2m.jpg",
    link: "https://shop.unyxgt.com/collections/cables",
  },
  {
    name: "Baterías Portátiles",
    count: 1,
    image: "/products/powerbank-130w-20000mah.jpg",
    link: "https://shop.unyxgt.com/collections/bateria-portatiles",
  },
  {
    name: "Accesorios",
    count: 3,
    image: "/products/mouse-vertical-m571p.jpg",
    link: "https://shop.unyxgt.com/collections/accesorios",
  },
  {
    name: "Audífonos",
    count: 2,
    image: "/products/audifonos-s3-clip.jpg",
    link: "https://shop.unyxgt.com/collections/audifonos",
  },
]
